version: "3.9"
services:
  certbot-netcup:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
        - ./:/var/certs:rw
    environment:
      # Configure netcup API login
      NETCUP_USER: xxxxx
      NETCUP_API_KEYID: your-api-key-id
      # NETCUP_API_SECRET: your-api-secret-but-better-export-this-external-instead-of-writing-it-into-a-compose-file
      
      # Configure CA and domains
      DIRECTORY: https://acme-v02.api.letsencrypt.org/directory
      DOMAINS: domain1.example.com,domain2.example.com,...
