name: Create and publish a Docker image

on:
  push:
  schedule:
    - cron: "17 17 * * *" # Run at 17:17 every day

env:
  REGISTRY: ghcr.io
  DOCKERFILE: Dockerfile
  IMAGE_TAG: kizzycode/acmesh-netcup:latest

jobs:
  build-and-push-image:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Login to Docker registry
        run: |
          docker login --username="${{ github.actor }}" --password="${{ secrets.GITHUB_TOKEN }}" "${{ env.REGISTRY }}"
      
      - name: Build the Docker image for linux/amd64
        run: |
          docker buildx build --file="${{ env.DOCKERFILE }}" --tag="${{ env.REGISTRY }}/${{ env.IMAGE_TAG }}" \
            --platform=linux/amd64 .
      
      - name: Build the Docker image for linux/arm64
        run: |
          docker buildx build --file="${{ env.DOCKERFILE }}" --tag="${{ env.REGISTRY }}/${{ env.IMAGE_TAG }}" \
            --platform=linux/arm64 .
      
      - name: Build the Docker image for linux/386
        run: |
          docker buildx build --file="${{ env.DOCKERFILE }}" --tag="${{ env.REGISTRY }}/${{ env.IMAGE_TAG }}" \
            --platform=linux/386 .

      - name: Push the Docker image
        run: |
          docker push "${{ env.REGISTRY }}/${{ env.IMAGE_TAG }}"
      